// Generate src/data/posts.js — the blog / message board feed — from whatever
// files live in content/blog/. Drop a .md, .txt, .docx or .pdf in that folder,
// push, and the Pages build (which runs this via `prebuild`) turns it into a
// post, newest at the top. PDFs/DOCX originals are copied into public/blog/ so
// they're served alongside the site.
//
// Ordering: a `YYYY-MM-DD` filename prefix wins; otherwise the file's last git
// commit date; otherwise its mtime. Titles: the first `# Heading` in a text
// file, else the (prettified) filename.
//
// Regenerate locally:  node scripts/gen-posts.mjs
import { readFileSync, writeFileSync, readdirSync, mkdirSync, copyFileSync, statSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { extname, basename, join } from 'node:path';
import { marked } from 'marked';
import mammoth from 'mammoth';

const SRC_DIR = 'content/blog';
const PUB_DIR = 'public/blog';      // served assets (pdf/docx originals)
const OUT = 'src/data/posts.js';
const SUPPORTED = new Set(['.md', '.markdown', '.txt', '.docx', '.pdf']);

mkdirSync(PUB_DIR, { recursive: true });

const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const prettify = (name) =>
  name.replace(/^\d{4}-\d{2}-\d{2}[-_ ]*/, '').replace(/[-_]+/g, ' ').replace(/\s+/g, ' ').trim()
    .replace(/\b\w/g, (c) => c.toUpperCase()) || name;

function fileDate(file, stem) {
  const m = stem.match(/^(\d{4}-\d{2}-\d{2})/);
  if (m) return m[1];
  try {
    const d = execSync(`git log -1 --format=%cs -- "${file}"`, { encoding: 'utf8' }).trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(d)) return d;
  } catch (e) { /* not committed yet */ }
  try { return statSync(file).mtime.toISOString().slice(0, 10); } catch (e) { return '1970-01-01'; }
}

const firstHeading = (text) => {
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim();
    if (!t) continue;
    const h = t.match(/^#{1,3}\s+(.*)$/);
    return h ? h[1].trim() : null;   // only treat a leading '# ' line as the title
  }
  return null;
};
const stripTags = (html) => html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
const excerptOf = (text, n = 200) => { const s = text.trim(); return s.length > n ? s.slice(0, n).replace(/\s+\S*$/, '') + '…' : s; };

async function buildPost(fname) {
  const ext = extname(fname).toLowerCase();
  const stem = basename(fname, ext);
  const full = join(SRC_DIR, fname);
  const date = fileDate(full, stem);
  const id = stem.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase();
  let title = prettify(stem);
  let html = '';
  let excerpt = '';

  if (ext === '.md' || ext === '.markdown') {
    const raw = readFileSync(full, 'utf8');
    const h = firstHeading(raw); if (h) title = h;
    html = marked.parse(raw, { mangle: false, headerIds: false });
    excerpt = excerptOf(stripTags(html));
  } else if (ext === '.txt') {
    const raw = readFileSync(full, 'utf8');
    const h = firstHeading(raw); if (h) title = h;
    html = raw.split(/\r?\n\r?\n+/).map((p) => `<p>${esc(p).replace(/\r?\n/g, '<br>')}</p>`).join('\n');
    excerpt = excerptOf(raw.replace(/^#{1,3}\s+.*(\r?\n)+/, ''));
  } else if (ext === '.docx') {
    const { value } = await mammoth.convertToHtml({ path: full });
    html = value || '';
    const h = stripTags(html).trim(); if (h) title = firstHeading(stripTags(html)) || title;
    // also offer the original for download
    copyFileSync(full, join(PUB_DIR, fname));
    html += `\n<p class="dl"><a href="blog/${encodeURIComponent(fname)}" download>⬇ download .docx</a></p>`;
    excerpt = excerptOf(stripTags(value || ''));
  } else if (ext === '.pdf') {
    copyFileSync(full, join(PUB_DIR, fname));
    const src = `blog/${encodeURIComponent(fname)}`;
    html = `<div class="pdf"><iframe src="${src}#view=FitH" title="${esc(title)}" loading="lazy"></iframe></div>` +
           `<p class="dl"><a href="${src}" target="_blank" rel="noopener">⬇ open / download PDF</a></p>`;
    excerpt = 'PDF document';
  }
  return { id, date, title, type: ext.slice(1), html, excerpt };
}

const files = readdirSync(SRC_DIR)
  .filter((f) => !f.startsWith('.') && f.toLowerCase() !== 'readme.md' && SUPPORTED.has(extname(f).toLowerCase()));

const posts = [];
for (const f of files) {
  try { posts.push(await buildPost(f)); }
  catch (e) { console.error(`skip ${f}: ${e.message}`); }
}
posts.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.title.localeCompare(b.title)));

const body =
  `// AUTO-GENERATED by scripts/gen-posts.mjs from content/blog/ — do not edit by hand.\n` +
  `// Add a .md/.txt/.docx/.pdf to content/blog/ and rebuild to post.\n` +
  `export const POSTS = ${JSON.stringify(posts, null, 0)};\n`;
writeFileSync(OUT, body);
console.log(`wrote ${OUT} — ${posts.length} post(s): ${posts.map((p) => p.date + ' ' + p.title).join(' | ')}`);
